CREATE TABLE `deseos` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`color` VARCHAR(7) NOT NULL DEFAULT '#16919c',
	`ttl` INT(11) UNSIGNED NOT NULL DEFAULT '0',
	`date_add` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;